SNP_SHARED_MAKEFILE := $(if $(SNP_SHARED_MAKEFILE),$(SNP_SHARED_MAKEFILE),~/snp/shared.mk)

TARGET     := bin/weekday
SOURCES    := src/main.c
TSTSOURCES := tests/tests.c

include $(SNP_SHARED_MAKEFILE)
